//
// Created by alireza on 10/25/21.
//

#ifndef FVLLMONTITRANSFORMER_SELFATTENTEST_H
#define FVLLMONTITRANSFORMER_SELFATTENTEST_H

#define D_Q 64
#define D_SEQ 512
#define D_MODEL 512

#endif //FVLLMONTITRANSFORMER_SELFATTENTEST_H
