//
// Created by alireza on 10/25/21.
//

#ifndef FVLLMONTITRANSFORMER_SELFATTENTEST_H
#define FVLLMONTITRANSFORMER_SELFATTENTEST_H

#define D_Q 32
#define D_SEQ 128
#define D_MODEL 64

#endif //FVLLMONTITRANSFORMER_SELFATTENTEST_H
