//
// Created by alireza on 10/25/21.
//

#ifndef FVLLMONTITRANSFORMER_TRANSFORMER_H
#define FVLLMONTITRANSFORMER_TRANSFORMER_H

#define D_Q 64
#define D_SEQ 256
#define D_MODEL 256
#define NUM_HEAD 4
#define D_FF 1024

#endif //FVLLMONTITRANSFORMER_TRANSFORMER_H
