//
// Created by alireza on 10/25/21.
//

#ifndef FVLLMONTITRANSFORMER_TRANSFORMER_H
#define FVLLMONTITRANSFORMER_TRANSFORMER_H

#define D_Q 64
#define D_SEQ 50
#define D_MODEL 768
#define NUM_HEAD 12
#define D_FF 3072

#endif //FVLLMONTITRANSFORMER_TRANSFORMER_H
